Added AstriDevCon 2024 page.
asterisk/documentation pull request #57
Opened 2024-02-21 19:34 UTC by bkford

Contains notes from devcon as well as some photos and other information.

2024-02-22 00:00 UTC, jcolp approved these changes

2024-02-22 13:18 UTC, gtjoseph requested changes

2024-02-22 13:18 UTC, gtjoseph commented on docs/Development/Roadmap/AstriDevCon-2024.md
> +-----------
I need to re-do the style guide but in the mean time...

Replace this with just...
```
# AstriDevCon 2024
```

2024-02-22 13:18 UTC, gtjoseph commented on docs/Development/Roadmap/AstriDevCon-2024.md
> +### Event day schedule
Replace all the `###` with `##`.

2024-02-28 10:13 UTC, jcolp approved these changes

2024-03-11 20:32 UTC, gtjoseph approved these changes

2024-03-11 20:33 UTC, merged